services:
  app:
    build:
      context: .
      dockerfile: ../Dockerfile
    container_name: laravel_app_combined
    ports:
      - "8080:80"
    volumes:
      - ..:/app
      - /app/vendor
    environment:
      PHP_DISPLAY_ERRORS: "1"
      PHP_MEMORY_LIMIT: "512M"
      WEB_DOCUMENT_ROOT: "/app/public"
    depends_on:
      - db
  db:
    image: mysql:8
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
